### ISSUE TITLE
Request: Is there a way to auto add \, when you press space while inside $$ ?

### ISSUE THREAD

**Issue by Eneswar** [joeyuping/quick_latex_obsidian#90] opened 2023-04-11 15:43 UTC

**Comment by joeyuping** [comment] 2023-04-11 16:32
Hi! @Eneswar 

sorry I wasnt really able to imagine a scenario for such a functionality.. would you kindly describe the use case that you are after?

**Comment by joeyuping** [comment] 2023-04-15 13:15
Hi @Eneswar !

I see I see... for such a use case, some might use `$text{500 meters}$` instead. But as you suggest, putting a slash works too. I am not so sure which one would be more common though. I could try to make an adjustment to the custom shorthand, so that it allows "space" as the shorthand for "\ ". That way, one can press space bar twice to create a "\ ". Might this work for you?

**Comment by Eneswar** [comment] 2023-04-15 13:35
Pressing space twice would be a very good solution, I would appreciate that very much.
This will only work inside the $$ tag right, and not outside, or outside too?

**Comment by joeyuping** [comment] 2023-05-29 00:31
Hi! 

please update to v2.6.2,  and add the following custom shorthand to the setting:

` :::\ ;`
(note the first space, then 3 colons, a slash, a space, finally a semicolon)
This way, within the $$ tag, you can press space twice (if right after text, then press space 3 times), the slash with space will be inserted. Hope this helps improve your workflow~

**Closed** 2023-05-29 00:31 UTC

**Comment by linuswalter** [comment] 2023-06-01 09:46
@joeyuping very nice implementation! I am using now the shortcut as ` :::\,;` to receive `\,`.
Super cool, thanks a lot! :heart:

**Comment by linuswalter** [comment] 2023-06-01 10:19
Sorry for just coming back to this @joeyuping, but actually I just realized that the standard custom shorthand commands do not work anymore when putting either ` :::\ ;` or ` :::\,;` into the list of custom shorthands.
Can you reproduce this issue or is it only in my setup?

**Comment by joeyuping** [comment] 2023-06-01 10:35
@linuswalter Hi! 

because there was a change of syntax after certain version before, the original shorthands on your side might be in the old syntax? that is, al:\alpha with only one colon?

if thats the case, could you use the old syntax instead, and add ' :\,;' to the shorthand?

**Comment by linuswalter** [comment] 2023-06-01 10:45
Ah, I understand! I switched to the new syntax now and it works perfectly. Thank you   @joeyuping :pray:
